# Generated by Django 6.0.1 on 2026-02-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_inventory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='product',
        ),
    ]
